### ISSUE TITLE
Releases are missing some Buttplug Library support files

### ISSUE THREAD

**Issue by qdot** [cyan-f/Plug_Parser#1]
Hi! qDot from Buttplug here. Someone just showed up on the discord asking for support on Plug_Parser, and I noticed your alpha release is missing a few support files that are required to run with Buttplug. You'll need to include the NewtonsoftJSON DLL and the NJSONSchema DLL.

If you need help getting that together, just lemme know, either here, or on Discord.

**Comment by cyan-f** [comment]
Thanks for letting me know. Fixed with 0.2.1a.
