### ISSUE TITLE
Buttplug NewtonsoftJson dependency not resolving correctly

### ISSUE THREAD

**Issue by qdot** [cyan-f/Plug_Parser#2]
Using 0.2.1a with ACT 3.3.4.259, I'm getting NewtonsoftJson versioning issues when trying to load the Plug_Parser plugin. Attached image shows the issue.

<img width="1176" alt="pp" src="https://user-images.githubusercontent.com/34539/59165502-7f4c1000-8ad1-11e9-9135-cc2acf6bf3b6.PNG">

This is coming from Buttplug trying to load its JSON parser. Not sure if a DLL binding reference needs to be added to the executable config or what quite yet, will try to poke around more on my end.

**Comment by cyan-f** [comment]
Hopefully fixed with 0.2.2a. The issue seems to be that I uploaded a more recent version of NJsonSchema.dll than the project supported with the release. Let me know if this fixed it.
